#!/usr/bin/env bash

JAR_PATH="$1"
DURATION_IN_MINUTES="$2"
DOCKS_ANOMALY_RATIO_IN_PERCENTS="$3"
BOOTSTRAP_SERVERS="$4"
APPLICATION_ID="$5"
INPUT_TOPIC_NAME="$6"
BICYCLE_STATIONS_FILEPATH="$7"

java -jar "$JAR_PATH" "$DURATION_IN_MINUTES" "$DOCKS_ANOMALY_RATIO_IN_PERCENTS" "$BOOTSTRAP_SERVERS" "$APPLICATION_ID" "$INPUT_TOPIC_NAME" "$BICYCLE_STATIONS_FILEPATH"
